### ISSUE TITLE
Error with awk when connecting to a client

### ISSUE THREAD

**Issue by valouille** [devopsprodigy/isolate#9]
Hello,

When I try to connect to a client, I get the following error :

`awk: /opt/auth/wrappers/timecode.awk: line 20: function systime never defined`

It appears that by default on Debian Stretch the awk command redirects to /usr/bin/mawk which doesn't recognize the systime command. I fixed the issue by installing gawk, which automatically becomes the default alternative for the awk command once installed. Maybe you should add gawk to the list of the packages installed by Ansible

Regards,

Valérian Beaudoin

**Comment by ghost** [comment]
https://github.com/itsumma/isolate/commit/da35e88c797bdd39ae0cd689a6ebd4e124e81c9d

fixed
